/*---------------------------------------------------------------------------
This list hasn't been updated in ages.
---------------------------------------------------------------------------*/
local ent = FindMetaTable("Entity")

local breakables = {
["models/props_c17/shelfunit01a.mdl"] = true,
["models/props_c17/oildrum001_explosive.mdl"] = true,
["models/props_c17/bench01a.mdl"] = true,
["models/props_c17/furnituredrawer001a_chunk01.mdl"] = true,
["models/props_c17/furnituredrawer001a_chunk02.mdl"] = true,
["models/props_c17/furnituredrawer001a_chunk03.mdl"] = true,
["models/props_c17/furnituretable001a.mdl"] = true,
["models/props_c17/furnituredrawer001a_chunk06.mdl"] = true,
["models/props_c17/furnitureshelf001b.mdl"] = true,
["models/props_c17/furnituredrawer002a.mdl"] = true,
["models/props_c17/furnituretable002a.mdl"] = true,
["models/gibs/furniture_gibs/furnituretable002a_chunk02.mdl"] = true,
["models/props_c17/furnituretable003a.mdl"] = true,
["models/gibs/furniture_gibs/furnituretable002a_chunk11.mdl"] = true,
["models/gibs/furniture_gibs/furnituretable003a_gib03.mdl"] = true,
["models/gibs/furniture_gibs/furnituretable003a_gib05.mdl"] = true,
["models/gibs/furniture_gibs/furnituretable003a_gib04.mdl"] = true,
["models/gibs/furniture_gibs/furniturewooddrawer003a_chunk03.mdl"] = true,
["models/gibs/furniture_gibs/furnituretable003a_gib01.mdl"] = true,
["models/gibs/furniture_gibs/furniturewooddrawer003a_chunk04.mdl"] = true,
["models/gibs/furniture_gibs/furniturewooddrawer003a_chunk02.mdl"] = true,
["models/gibs/furniture_gibs/furnituretable002a_chunk08.mdl"] = true,
["models/gibs/furniture_gibs/furnituretable002a_chunk03.mdl"] = true,
["models/gibs/furniture_gibs/furnituretable002a_chunk07.mdl"] = true,
["models/gibs/furniture_gibs/furnituredrawer002a_gib05.mdl"] = true,
["models/gibs/furniture_gibs/furniturewooddrawer003a_chunk01.mdl"] = true,
["models/gibs/furniture_gibs/furniturewooddrawer003a_chunk05.mdl"] = true,
["models/gibs/furniture_gibs/furnituredrawer002a_gib03.mdl"] = true,
["models/gibs/furniture_gibs/furnituredrawer002a_gib07.mdl"] = true,
["models/gibs/furniture_gibs/furnituredrawer002a_gib06.mdl"] = true,
["models/props_interiors/furniture_desk01a.mdl"] = true,
["models/props_junk/cardboard_box003a.mdl"] = true,
["models/props_junk/cardboard_box004a.mdl"] = true,
["models/props_junk/wood_crate001a_chunk07.mdl"] = true,
["models/props_junk/wood_crate001a_chunk02.mdl"] = true,
["models/props_junk/wood_crate001a_chunk09.mdl"] = true,
["models/props_junk/wood_pallet001a.mdl"] = true,
["models/props_wasteland/barricade001a_chunk03.mdl"] = true,
["models/props_wasteland/barricade001a_chunk01.mdl"] = true,
["models/props_wasteland/barricade002a_chunk02.mdl"] = true,
["models/props_wasteland/barricade002a_chunk05.mdl"] = true,
["models/props_wasteland/barricade002a_chunk06.mdl"] = true,
["models/props_wasteland/wood_fence02a_board05a.mdl"] = true,
["models/props_wasteland/wood_fence02a_board01a.mdl"] = true,
["models/props_wasteland/wood_fence02a_board10a.mdl"] = true,
["models/props_interiors/furniture_chair01a.mdl"] = true,
["models/gibs/furniture_gibs/furniture_chair01a_gib03.mdl"] = true,
["models/props_junk/wood_crate001a_chunk01.mdl"] = true,
["models/props_interiors/furniture_vanity01a.mdl"] = true,
["models/gibs/furniture_gibs/furniture_vanity01a_gib01.mdl"] = true,
["models/props_junk/watermelon01_chunk01b.mdl"] = true,
["models/props_junk/garbage_coffeemug001a.mdl"] = true,
["models/props_junk/gascan001a.mdl"] = true,
["models/props_junk/glassbottle01a.mdl"] = true,
["models/props_junk/garbage_glassbottle001a.mdl"] = true,
["models/props_junk/garbage_glassbottle003a.mdl"] = true,
["models/props_combine/breenbust.mdl"] = true,
["models/props/cs_militia/bottle01.mdl"] = true,
["models/props/cs_office/coffee_mug.mdl"] = true,
["models/props/cs_office/snowman_face.mdl"] = true,
["models/props/cs_office/computer_caseb_p1.mdl"] = true,
["models/items/item_item_crate_chunk06.mdl"] = true,
["models/items/item_item_crate_chunk07.mdl"] = true,
["models/items/item_item_crate_chunk01.mdl"] = true,
["models/items/item_item_crate_chunk02.mdl"] = true,
["models/props_forest/sawhorse.mdl"] = true,
["models/props_canal/boat001a_chunk07.mdl"] = true,
["models/props_canal/boat001a_chunk01.mdl"] = true,
["models/props_canal/boat001a_chunk010.mdl"] = true,
["models/props_canal/boat001a_chunk09.mdl"] = true,
["models/props_canal/boat001b_chunk06.mdl"] = true,
["models/props_canal/boat001b_chunk03.mdl"] = true,
["models/props_canal/boat001b_chunk07.mdl"] = true,
["models/items/item_item_crate_chunk05.mdl"] = true,
["models/items/item_item_crate_chunk09.mdl"] = true,
["models/items/item_item_crate_chunk08.mdl"] = true,
["models/props_phx/construct/glass/glass_plate2x2.mdl"] = true,
["models/props_canal/boat001a_chunk08.mdl"] = true,
["models/props_canal/boat001a_chunk06.mdl"] = true,
["models/props_canal/boat001b_chunk01.mdl"] = true,
["models/props_phx/cannonball.mdl"] = true,
["models/props/cs_office/table_coffee_p2.mdl"] = true,
["models/props/cs_office/table_coffee_p3.mdl"] = true,
["models/props_phx/amraam.mdl"] = true,
["models/props_phx/misc/egg.mdl"] = true,
["models/props_canal/boat001a_chunk04.mdl"] = true,
["models/gibs/furniture_gibs/furniture_vanity01a_gib02.mdl"] = true,
["models/props_c17/furnituredrawer001a.mdl"] = true,
["models/props_c17/furnituredrawer001a_chunk05.mdl"] = true,
["models/gibs/furniture_gibs/furniture_vanity01a_gib05.mdl"] = true,
["models/props_c17/furnituredresser001a.mdl"] = true,
["models/props_wasteland/barricade001a.mdl"] = true,
["models/props_wasteland/barricade001a_chunk02.mdl"] = true,
["models/props_wasteland/barricade001a_chunk04.mdl"] = true,
["models/props_wasteland/barricade002a.mdl"] = true,
["models/props_wasteland/wood_fence01a.mdl"] = true,
["models/props_wasteland/wood_fence02a_board09a.mdl"] = true,
["models/props_wasteland/wood_fence02a_board08a.mdl"] = true,
["models/props_wasteland/wood_fence02a_board04a.mdl"] = true,
["models/props_wasteland/wood_fence02a_board03a.mdl"] = true,
["models/props_wasteland/wood_fence02a.mdl"] = true,
["models/props_junk/wood_crate001a.mdl"] = true,
["models/props_junk/wood_crate001a_chunk03.mdl"] = true,
["models/props_junk/wood_crate001a_chunk04.mdl"] = true,
["models/props_junk/wood_crate001a_chunk05.mdl"] = true,
["models/props_junk/wood_crate002a.mdl"] = true,
["models/props_wasteland/barricade002a_chunk01.mdl"] = true,
["models/props_wasteland/barricade002a_chunk03.mdl"] = true,
["models/props_wasteland/barricade002a_chunk04.mdl"] = true,
["models/props_interiors/furniture_couch02a.mdl"] = true,
["models/gibs/furniture_gibs/furniture_chair01a_gib05.mdl"] = true,
["models/gibs/furniture_gibs/furniture_chair01a_gib01.mdl"] = true,
["models/gibs/furniture_gibs/furniture_chair01a_gib02.mdl"] = true,
["models/props_c17/furnitureshelf001a.mdl"] = true,
["models/props_wasteland/prison_shelf002a.mdl"] = true,
["models/props_wasteland/barricade001a_chunk05.mdl"] = true,
["models/props_junk/propane_tank001a.mdl"] = true,
["models/props_interiors/furniture_shelf01a.mdl"] = true,
["models/gibs/furniture_gibs/furniture_vanity01a_gib03.mdl"] = true,
["models/props_c17/furnituredrawer003a.mdl"] = true,
["models/props_c17/furniturechair001a.mdl"] = true,
["models/props_c17/furniturechair001a_chunk02.mdl"] = true,
["models/props_junk/watermelon01.mdl"] = true,
["models/props_junk/watermelon01_chunk01c.mdl"] = true,
["models/props_junk/watermelon01_chunk01a.mdl"] = true,
["models/props_interiors/furniture_couch01a.mdl"] = true,
["models/props_c17/furniturechair001a_chunk01.mdl"] = true,
["models/props_c17/furniturechair001a_chunk03.mdl"] = true,
["models/props_junk/wood_crate001a_damaged.mdl"] = true,
["models/props/cs_militia/barstool01.mdl"] = true,
["models/props/cs_militia/skylight_glass.mdl"] = true,
["models/props/cs_militia/wndw01.mdl"] = true,
["models/props/cs_militia/wndw01.mdl"] = true,
["models/props/cs_office/tv_plasma.mdl"] = true,
["models/props/cs_office/plant01.mdl"] = true,
["models/props/de_inferno/windowbreakable_02.mdl"] = true,
["models/props/de_inferno/windowbreakable.mdl"] = true,
["models/props/de_inferno/wine_barrel.mdl"] = true,
["models/props_phx/misc/potato_launcher_explosive.mdl"] = true,
["models/props_phx/misc/flakshell_big.mdl"] = true,
["models/props_phx/construct/glass/glass_angle180.mdl"] = true,
["models/props_phx/construct/glass/glass_angle360.mdl"] = true,
["models/props_phx/construct/glass/glass_angle90.mdl"] = true,
["models/props_phx/construct/glass/glass_curve180x2.mdl"] = true,
["models/props_phx/construct/glass/glass_curve360x1.mdl"] = true,
["models/props_phx/construct/glass/glass_curve360x2.mdl"] = true,
["models/props_phx/construct/glass/glass_curve90x1.mdl"] = true,
["models/props_phx/construct/glass/glass_dome360.mdl"] = true,
["models/props_phx/construct/glass/glass_plate1x1.mdl"] = true,
["models/props_phx/construct/glass/glass_plate1x2.mdl"] = true,
["models/props_phx/construct/glass/glass_plate2x2.mdl"] = true,
["models/props_phx/construct/glass/glass_plate2x4.mdl"] = true,
["models/props_phx/construct/glass/glass_plate4x4.mdl"] = true,
["models/props_phx/construct/wood/wood_angle180.mdl"] = true,
["models/props_phx/construct/wood/wood_angle360.mdl"] = true,
["models/props_phx/construct/wood/wood_boardx1.mdl"] = true,
["models/props_phx/construct/wood/wood_boardx2.mdl"] = true,
["models/props_phx/construct/wood/wood_curve180x1.mdl"] = true,
["models/props_phx/construct/wood/wood_boardx4.mdl"] = true,
["models/props_phx/construct/wood/wood_curve360x2.mdl"] = true,
["models/props_phx/construct/wood/wood_curve90x1.mdl"] = true,
["models/props_phx/construct/wood/wood_dome180.mdl"] = true,
["models/props_phx/construct/wood/wood_dome90.mdl"] = true,
["models/props_phx/construct/wood/wood_panel1x1.mdl"] = true,
["models/props_phx/construct/wood/wood_panel1x2.mdl"] = true,
["models/props_phx/construct/wood/wood_panel2x2.mdl"] = true,
["models/props_phx/construct/wood/wood_wire_angle90x2.mdl"] = true,
["models/props_phx/construct/wood/wood_wire_angle90x1.mdl"] = true,
["models/props_phx/construct/wood/wood_wire_angle360x2.mdl"] = true,
["models/props_phx/construct/wood/wood_wire_angle360x1.mdl"] = true,
["models/props_phx/construct/wood/wood_wire2x2b.mdl"] = true,
["models/props_phx/construct/wood/wood_wire1x2x2b.mdl"] = true,
["models/props_phx/construct/wood/wood_wire1x2.mdl"] = true,
["models/props_phx/construct/wood/wood_wire1x1x2.mdl"] = true,
["models/props_phx/construct/wood/wood_panel2x4.mdl"] = true,
["models/props_phx/construct/wood/wood_panel4x4.mdl"] = true,
["models/props_phx/construct/wood/wood_wire1x1.mdl"] = true,
["models/props_phx/construct/wood/wood_wire1x1x1.mdl"] = true,
["models/props_phx/construct/wood/wood_wire1x1x2b.mdl"] = true,
["models/props_phx/ww2bomb.mdl"] = true,
["models/props_phx/torpedo.mdl"] = true,
["models/props_phx/ball.mdl"] = true,
["models/props_phx/oildrum001_explosive.mdl"] = true,
["models/props_phx/mk-82.mdl"] = true
}

function ent:IsBreakable()
	return breakables[string.lower(self:GetModel())]
	/*if table.HasValue(breakables, string.lower(self:GetModel())) then
		return true
	end
	return false*/
end

local function FindBreakables(attacker, prop)
	if not IsValid(prop) then return end
	local File = file.Read("breakableprops.txt") or ""

	if not IsValid(prop) or string.find(File, string.lower(prop:GetModel() or "")) then return end
	file.Write("breakableprops.txt",File.. "\""..prop:GetModel().."\",\n")
end
hook.Add("PropBreak", "FindBreakables", FindBreakables)